### ISSUE TITLE
大佬，怎么让群主和管理员也能参与呀

### ISSUE THREAD

**Issue by yaoxiaosa** [EvolvedGhost/MuteGames#2]
群主和管理员发送指令没有反应啊

**Comment by yaoxiaosa** [comment]
群友说之前见过管理员可以参与，但是不吃禁言的群

**Comment by EvolvedGhost** [comment]
新版本可以通过将`AdminConfig.kt`中的`canAdminPlayIt`设置为`true`让机器人禁言不到的用户游玩
